version: '3.8'

services:
  frontend:
    build: ./client
    container_name: frontend-app
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build: ./server
    container_name: backend-api
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped
