- name: Setup Dockerized React + Node.js App
  hosts: web
  become: true
  vars_files:
    - secrets.yml  # Encrypted file with environment variables

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - git
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add azureuser to docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Ensure app directory exists
      file:
        path: /home/azureuser/app
        state: directory
        owner: azureuser
        group: azureuser
        recurse: yes

    - name: Mark /home/azureuser/app as a safe Git directory
      shell: git config --global --add safe.directory /home/azureuser/app
      become_user: azureuser

    - name: Clone the GitHub repo
      git:
        repo: 'https://github.com/JNilukshan/user-registration-app.git'
        dest: /home/azureuser/app
        version: main
        force: yes
        update: yes
        accept_hostkey: yes
      become_user: azureuser

    - name: Create .env file for backend from encrypted vars
      copy:
        dest: /home/azureuser/app/server/.env
        content: |
          PORT={{ PORT }}
          MONGO_URI={{ MONGO_URI }}
          TWILIO_ACCOUNT_SID={{ TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN={{ TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM={{ TWILIO_WHATSAPP_FROM }}
          GDRIVE_FOLDER_ID={{ GDRIVE_FOLDER_ID }}
        owner: azureuser
        group: azureuser
        mode: '0644'

    - name: Run docker-compose up (build + start containers)
      shell: docker-compose up -d --build
      args:
        chdir: /home/azureuser/app
      become_user: azureuser
